### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cmnstmntmn** [DeuxHuitHuit/multilingual_image_upload#9]
```
Symphony Fatal Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3
```

An error occurred while attempting to execute the following query
```
SELECT SQL_CACHE value, field_ FROM entries_data_21 WHERE entry_id=
```

Latest SymphonyCMS, image upload field and multilanguage image upload

**Comment by cmnstmntmn** [comment]
i guess is more an image upload issue, as far as i tested with an image upload field

same issue [here](https://github.com/DeuxHuitHuit/image_upload/issues/31)

**Comment by nitriques** [comment]
This is a order_entries problem.
